const GET_ALL_ORDERS = "GET_ALL_ORDERS";
const REMOVE_ORDER = "REMOVE_ORDER";

const ADD_PRODUCT = "ADD_PRODUCT";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export { GET_ALL_ORDERS, REMOVE_ORDER, ADD_PRODUCT, REMOVE_PRODUCT };
