const GET_ALL_ORDERS = "GET_ALL_ORDERS";
const REMOVE_ORDER = "REMOVE_ORDER";
const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";

const ADD_PRODUCT = "ADD_PRODUCT";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export {
  GET_ALL_ORDERS,
  REMOVE_ORDER,
  ADD_ORDER_ITEM,
  REMOVE_ORDER_ITEM,
  ADD_PRODUCT,
  GET_ALL_PRODUCTS,
  REMOVE_PRODUCT,
};
